{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dotnet-boilerplate-api.postgresql.fullname" . }}
  labels:
    {{- include "dotnet-boilerplate-api.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.auth.secretKeys.passwordKey }}: {{ required "postgresql.auth.password is required when postgresql.auth.existingSecret is not set" .Values.postgresql.auth.password | quote }}
{{- end }}
