{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet-boilerplate-api.postgresql.fullname" . }}
  labels:
    {{- include "dotnet-boilerplate-api.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "dotnet-boilerplate-api.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
